In [54]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [55]:
data = pd.read_csv('./Prac5_Social_Network_Ads.csv')

In [56]:
data = data.drop('User ID', axis=1)

In [57]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data['Gender'] = le.fit_transform(data['Gender'])
print(data)

     Gender  Age  EstimatedSalary  Purchased
0         1   19            19000          0
1         1   35            20000          0
2         0   26            43000          0
3         0   27            57000          0
4         1   19            76000          0
..      ...  ...              ...        ...
395       0   46            41000          1
396       1   51            23000          1
397       0   50            20000          1
398       1   36            33000          0
399       0   49            36000          1

[400 rows x 4 columns]


In [58]:
x = data.iloc[:, :-1].values
y = data.iloc[:, -1:].values

In [59]:
print(x)

[[    1    19 19000]
 [    1    35 20000]
 [    0    26 43000]
 ...
 [    0    50 20000]
 [    1    36 33000]
 [    0    49 36000]]


In [60]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [71]:
print(type(x_train))
print(data.dtypes)
print(x_train)
import numpy as np
print(np.isnan(x_train).sum())

<class 'numpy.ndarray'>
Gender             int64
Age                int64
EstimatedSalary    int64
Purchased          int64
dtype: object
[[ 1.02532046e+00  1.92295008e+00  2.14601566e+00]
 [-9.75304830e-01  2.02016082e+00  3.78719297e-01]
 [-9.75304830e-01 -1.38221530e+00 -4.32498705e-01]
 [-9.75304830e-01 -1.18779381e+00 -1.01194013e+00]
 [-9.75304830e-01  1.92295008e+00 -9.25023920e-01]
 [-9.75304830e-01  3.67578135e-01  2.91803083e-01]
 [-9.75304830e-01  1.73156642e-01  1.46942725e-01]
 [ 1.02532046e+00  2.02016082e+00  1.74040666e+00]
 [-9.75304830e-01  7.56421121e-01 -8.38107706e-01]
 [-9.75304830e-01  2.70367388e-01 -2.87638347e-01]
 [ 1.02532046e+00  3.67578135e-01 -1.71750061e-01]
 [-9.75304830e-01 -1.18475597e-01  2.20395980e+00]
 [-9.75304830e-01 -1.47942605e+00 -6.35303205e-01]
 [ 1.02532046e+00 -1.28500455e+00 -1.06988428e+00]
 [ 1.02532046e+00 -1.38221530e+00  4.07691369e-01]
 [-9.75304830e-01 -1.09058306e+00  7.55356227e-01]
 [ 1.02532046e+00 -1.47942605e+00 -2.00722133e

In [62]:
sc = StandardScaler()
print(x_train)
print(x_test)
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
print(x_train)
print(x_test)

[[     1     58 144000]
 [     0     59  83000]
 [     0     24  55000]
 [     0     26  35000]
 [     0     58  38000]
 [     0     42  80000]
 [     0     40  75000]
 [     1     59 130000]
 [     0     46  41000]
 [     0     41  60000]
 [     1     42  64000]
 [     0     37 146000]
 [     0     23  48000]
 [     1     25  33000]
 [     1     24  84000]
 [     0     27  96000]
 [     1     23  63000]
 [     1     48  33000]
 [     1     48  90000]
 [     1     42 104000]
 [     0     44  39000]
 [     1     32 120000]
 [     0     38  50000]
 [     0     32 135000]
 [     0     52  21000]
 [     0     53 104000]
 [     1     39  42000]
 [     1     38  61000]
 [     0     36  50000]
 [     0     36  63000]
 [     0     35  25000]
 [     1     35  50000]
 [     1     42  73000]
 [     0     47  49000]
 [     0     59  29000]
 [     1     49  65000]
 [     0     45 131000]
 [     0     31  89000]
 [     0     46  82000]
 [     0     47  51000]
 [     1     26  15000]
 [     1     60 

In [64]:
model = LogisticRegression()
model.fit(x_train, y_train)

C:\Users\Aniruddha\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [66]:
y_pred = model.predict(x_test)
print(y_pred)

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0
 0 0 1 0 1 1]


In [67]:
cm = confusion_matrix(y_test, y_pred)
TN, FP, FN, TP = cm.ravel()

In [68]:
accuracy = (TP + TN) / (TP+TN+FP+FN)
error_rate = 1 - accuracy
precision = TP / (TP+FP)
recall = TP / (TP+FN)

In [70]:
print("Confusion Matrix:\n", cm)
print("TP:", TP, "FP:", FP, "TN:", TN, "FN:", FN)
print("Accuracy:", accuracy)

Confusion Matrix:
 [[56  2]
 [ 5 17]]
TP: 17 FP: 2 TN: 56 FN: 5
Accuracy: 0.9125
